ALTER TABLE `link`
	ADD COLUMN `user_id` BIGINT NULL DEFAULT NULL AFTER `category_id`,
	ADD CONSTRAINT `FK_link_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;