ALTER TABLE `category`
	ADD COLUMN `user_id` BIGINT NULL DEFAULT NULL AFTER `status`,
	ADD CONSTRAINT `FK_category_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;